name: CI Pipeline

on:
  push:
    branches: [ master, lab3 ]
  pull_request:
    branches: [ master, lab3 ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_python

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8

      - name: Run Linter
        run: flake8 --count --statistics --show-source --ignore=E501

      - name: Run Tests
        run: pytest --maxfail=5 --disable-warnings

  docker:
    needs: build-test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        run: |
          docker build -f app_python/python.Dockerfile -t ${{ secrets.DOCKER_USERNAME }}/app-python:latest ./app_python
          docker push ${{ secrets.DOCKER_USERNAME }}/app-python:latest
