name: CI Pipeline

on:
  push:
    branches: [ master, lab3 ]
  pull_request:
    branches: [ master, lab3 ]

jobs:
  build-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: app_python

    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
          cache: 'pip'

      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 snyk

      - name: Run Linter
        run: flake8 --count --statistics --show-source --ignore=E501

      - name: Run Tests
        run: pytest --maxfail=5 --disable-warnings

  security-scan:
    runs-on: ubuntu-latest
    needs: build-test
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Run Snyk Security Scan
        uses: snyk/actions/python@master
        with:
          args: --file=requirements.txt
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

  docker:
    runs-on: ubuntu-latest
    needs: [build-test, security-scan]
    steps:
      - name: Checkout Code
        uses: actions/checkout@v3

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push Docker Image
        uses: docker/build-push-action@v4
        with:
          context: app_python
          file: app_python/python.Dockerfile
          push: true
          tags: ${{ secrets.DOCKER_USERNAME }}/app-python:latest
          cache-from: type=registry,ref=${{ secrets.DOCKER_USERNAME }}/app-python:latest
          cache-to: type=inline
